FROM node:12.18.1

WORKDIR /app

COPY /backend-payments/package.json /app/

RUN npm i

COPY .env /app/
COPY /backend-payments/src/ /app/src/
COPY /backend-payments/test/ /app/test/
COPY /deployments /app/deployments

ENV NODE_ENV=development
