version: '3.5'

volumes:
  deployments:

networks:
  dev-net:
    driver: bridge

services:
  web:
    container_name: web_pay_cont
    build:
      context: .
      dockerfile: Dockerfile.dev-web
    depends_on:
      - sc
    entrypoint: /app/docker-entrypoint-dev.sh
    environment:
      - SC_HH_NODE_URL=http://sc:8545
      # sc is the name of the sc service and it will be
      # translated to its Ipv4 address by docker-compose
      # engine
      - PORT=5002
    ports:
      - 5002:5002
    volumes:
      - deployments:/app/deployments
      - ./backend-payments/src/:/app/src/
      - ./backend-payments/test/:/app/test/
    networks:
      - dev-net

  sc:
    container_name: sc_cont
    build:
      context: .
      dockerfile: Dockerfile.dev-sc
    command: npx hardhat node
    # This command will also find and deploy the smart-contract
    # (This is true if the folders are arranged like in this repository;
    # for another folder structure it might as well be true, but it was
    # not tested yet)
    volumes:
      - deployments:/app/deployments
    networks:
      - dev-net

