name: All

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: 
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "MNEMONIC='${MNEMONIC}'" >> .env
          echo "INFURA_API_KEY='${INFURA_API_KEY}'" >> .env
          cat .env
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      - name: Build docker image
        run: |
          docker build . -t smart-contract-image
      - name: Run tests inside container
        run: |
          docker run --rm smart-contract-image npm test
