name: All

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: 
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo MNEMONIC=$MNEMONIC >> .env
          echo INFURA_API_KEY=$INFURA_API_KEY >> .env
        shell: bash
        env:
          MNEMONIC: ${{secrets.MNEMONIC}}
          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
      - name: Build containers
        run: |
          docker-compose build
      - name: Start services
        run: |
          docker-compose up -d
      - name: Test Smart Contract
        run: |
          docker-compose exec -T hh_node npm test
      - name: Test Backend Payments
        run: |
          docker-compose exec -T web npm test
